### ISSUE TITLE
No bonus chest overlay

### ISSUE THREAD

**Issue by spythonor** [sololegends/runelite-varlamore-house-thieving#13]
Bonus chest overlay is not appearing as of the last 24 hours. I turned off Arceus library plugin based on some old comments but it made no difference.

**Comment by sololegends** [comment]
The overlay meaning the highlighted border, the arrow indicator, or both?  

Can you ensure you have the "Bonus chest overlay" configuration option ticked "On"?

**Comment by spythonor** [comment]
Yes, both options are checked, and the bonus chest is not highlighted nor is there an arrow indicating it anymore. FWIW I don't see the bots that have been here the last week, so it's possible Jagex may have made a stealth update that broke the plugin? just speculation though

**Comment by sololegends** [comment]
I've tested it today and I couldn't replicate your issue. So I don't think it is generally broken at least 

The chest highlighting is solely based on that hint arrow, which is a vanilla thing, and other plugins can randomly clear it if they like. 

I'm looking into other ways to detect it because of all these issues with the hint arrow. >.< 

Did you install or change any other plugins in the last 24hrs?

**Comment by sololegends** [comment]
Sorry I don't have better info for you. I'll keep looking for some way this could be happening. And look for a way to detect it without the arrow (and maybe make my own arrow)
