### ISSUE TITLE
Highlights flashing

### ISSUE THREAD

**Issue by Pesofvati** [sololegends/runelite-varlamore-house-thieving#9]
If you are inside the southeastern house when Aurelia is distracting a Wealthy Citizen, your highlights will flash between house thieving and citizen thieving.
Can be fixed manually by toggling wealthy citizen and distracted citizen highlighting options when house thieving.
(This started after the update two days ago)

**Comment by sololegends** [comment]
Thanks for the report I'll look into this

**Comment by sololegends** [comment]
I'm trying to figure out what the issue is here, though I'm struggling to do so. 

You say: 
> highlights will flash between house thieving and citizen thieving   

However I'm seeing consistent highlighting for non-distracted and distracted citizens.  
This icon above the citizen's head **is** supposed to flash if that is to what you are referring. 
![image](https://github.com/user-attachments/assets/156d19e4-72ce-42dd-bb6d-9098f805f728)

I've added options now to turn off the flashing and disable the icon whilst inside the house. (Next update) 

Let me know if this was not your issue.
